# Generated by Django 3.1.7 on 2021-12-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='未付款', max_length=16, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(verbose_name='价格'),
        ),
    ]
